# Generated by Django 2.0 on 2018-03-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image_uri', models.URLField(blank=True)),
                ('exercise_type', models.IntegerField(choices=[(0, 'RestType'), (1, 'LiftType'), (2, 'BodyweightType'), (3, 'IntervalType')])),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('exercise_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_groups_rel', to='workouts.ExerciseActivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_group_links_rel', to='workouts.Exercise')),
                ('exercise_set_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_group_links_rel', to='workouts.ExerciseSetGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(blank=True, null=True)),
                ('exercise_set_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_instances_rel', to='workouts.ExerciseSetGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('param_name', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_params_rel', to='workouts.Exercise')),
                ('exercise_set_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_params_rel', to='workouts.ExerciseSetInstance')),
            ],
        ),
        migrations.AddField(
            model_name='exercisesetgroup',
            name='exercises',
            field=models.ManyToManyField(related_name='set_groups_rel', through='workouts.ExerciseSetGroupLink', to='workouts.Exercise'),
        ),
        migrations.AddField(
            model_name='exerciseactivity',
            name='exercise_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_rel', to='workouts.ExerciseSession'),
        ),
    ]
